### ISSUE TITLE
cputype in the wiki

### ISSUE THREAD

**Issue by ghost** [Wikiemol/Mach-O-64#1]
Really happy to find your wiki, it's explaining lots of stuff I wanted to know about Mach-O Files. 
I am wondering though because I was looking at the cputype and you said there are 3 possible values 0x00, 0x01 and 0x02 but I was looking at [this](http://llvm.org/doxygen/Support_2MachO_8h_source.html) and I found a bunch of other types:

```
 // Constants for the cputype field.
 1424     enum CPUType {
 1425       CPU_TYPE_ANY       = -1,
 1426       CPU_TYPE_X86       = 7,
 1427       CPU_TYPE_I386      = CPU_TYPE_X86,
 1428       CPU_TYPE_X86_64    = CPU_TYPE_X86 | CPU_ARCH_ABI64,
 1429    /* CPU_TYPE_MIPS      = 8, */
 1430       CPU_TYPE_MC98000   = 10, // Old Motorola PowerPC
 1431       CPU_TYPE_ARM       = 12,
 1432       CPU_TYPE_ARM64     = CPU_TYPE_ARM | CPU_ARCH_ABI64,
 1433       CPU_TYPE_SPARC     = 14,
 1434       CPU_TYPE_POWERPC   = 18,
 1435       CPU_TYPE_POWERPC64 = CPU_TYPE_POWERPC | CPU_ARCH_ABI64
```

I am probably just being dumb and missing something but I wonder if you could explain. Or are these types maybe not supported anymore?

I was mainly curious because I was (and still haven't finished copying out for going down rabbit holes) trying out [this](http://osxbook.com/blog/2009/03/15/crafting-a-tiny-mach-o-executable/) and the cputype there was 7. But I mean to be fair it's pretty old and once I try and run it I might find that it doesn't work anymore.

**Comment by Wikiemol** [comment]
Ah okay great question! I am guessing you are referring to this:

> The first byte of cputype is the ABI address size, which can currently take on three possible values in mac os x. CPU_ARCH_ABI64 = 0x01, CPU_ARCH_ABI64_32 = 0x02 or 0x0 which (I am guessing) represents a 32 bit ABI.

So, I realized that I worded that section badly. The key point is that the first _byte_ can take on 3 values. The rest of the field is what that enum refers to. The enum is made by ORing the first 3 bytes with the rest of the field (you can see that in CPU_TYPE_X86_64 which is CPU_TYPE_X86 | CPU_ARCH_ABI_64). I should probably rewrite this section so that it makes a bit more sense.

**Comment by ghost** [comment]
Oh yeah sorry, that's what I get for skimming! That makes much more sense.
